export interface IAlert {
    sdaId: string;
    sdrNumber?: string;
    createDate: Date;
    lineMaintenance: boolean;
    alertCode: string;
    ataCode1: string;
    ataCode2: string;
    aircraftNo: string;
    station: string;
    department: string;
    manufacturer: string;
    model: string;
    serialNo: string;
    totalShipTime: string;
    cycles: string;
    fleet: string;
    scheduledMaintenance?: boolean;
    nonRoutineNo: string;
    micNo: string;
    checkType: string;
    routineNo: string;
    unscheduledDescription: string;
    defectType: string;
    defectDescription: string;
    length: string;
    width: string;
    depth: string;
    stationLocation: string;
    stringer: string;
    wl: string;
    bl: string;
    MFGpart: string;
    partDefective: string;
    MFGserial: string;
    PartTT: string;
    PartTso: string;
    detected: string;
    status:number;
    statusText:string;

}
