export interface IGeneralSection {
  versionID?: number;
  sdrNumber?: string;
  station?: string;
  department?: number;
  aircraftNo?: string;
  aircraftRegistrationNo?: string;
  manufacturer?: string;
  model?: string;
  serialNo?: string;
  totalShipTime?: string;
  cycles?: string;
  fleet?: string;
  originator?: string;
  originatorBadgeNo?: string;
  lineMaintenance?: boolean;
  alertCode?: number;
  ataCode1?: number;
  ataCode2?: number;
  defectDiscoveredDuring?: string;
  unscheduledMaintenanceDescription?: string;
  checkType?: number;
  checkTypeOtherText?: string;
  routineNo?: string;
  nonRoutineNo?: string;
  esmReference?: string;
  micNo?: string;
  createDate?: Date;
}
