export interface ISearchByDTE {
  dteStatus?: any;
  dteStatusNull?: boolean;
  totalShipTimeFrom?: any;
  totalShipTimeTo?: any;
  cyclesFrom?: any;
  cyclesTo?: any;
  repairInspectionStatus?: any;
  isFatigueCritical?: any;
  stage1RTSDateFrom?: any;
  stage1RTSDateTo?: any;
  stage1Duration?: any;
  stage2DateFrom?: any;
  stage2DateTo?: any;
  stage3DateFrom?: any;
  Stage3DateTo?: any;
  srNumber?: any;
  rdasNumber?: any;
  etdNumber?: any;
  esmSubItemNumber?: any;
  inspectionThreshold?: any;
  inspectionInterval?: any;
  inspectionMethod?: any;
  monitorItemDescription?: any;
  comments?: any;
  qcFeedback?: any;
  submittedToQC?: any;
  updatedBy?: any;
  updatedDateFrom?: any;
  updatedDateTo?: any;
  dueDateFrom?: any;
  dueDateTo?: any;
  dueDateCompleted?: any;
  taskCardNo?: string;
  repairDateFrom?: Date;
  repairDateto?: Date;
  airlineCode?: string;
  removedByDateFrom?: Date;
  removedByDateTo?: Date;
  mrbNumber?: string;
  mrtNumber?: string;
  removedByMrt?: string;
  status?: number;
  zone?: string;
  repairLocation?: string;
  mroDocuments?: string;
  legacyEA?: string;
  componentType?: number;
  controlOrderNumber?: string,
  componentAAID?: string,
  componentSerialNumber?: string,
  cmbNumber?: string;
  compForAircraft?: string;
  componentRspam?: string,
  componentMpn?: string,
  componentHours?: string,
  componentCycles?: string
  onOffWing?: string;
  rack?: string;
  engPsn?: string;
  engCycles?: string;
  engHours?: string;
  engRspam?: string;
  engSn?: string;
  engMpn?: string;
}
