import { Injectable } from '@angular/core';
import { Http } from '@angular/http';
import { Observable } from 'rxjs/Observable';
import { List } from "immutable";
import { environment } from '../../../environments/environment';
import { ISDAForm } from '../models/sda-form.model';
import '../rxjs-extensions';

@Injectable()
export class SdaFormService {
    private endPointUrl = `${environment.hsdaApiBaseUrl}SdaForm`;
    constructor(private http: Http) { }
    getSdaForm(id: string): Observable<ISDAForm> {

        var forms =[
            {
                sdaId: '123456',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1:'52-Doors',
                ataCode2:'30 Cargo Door',
                model:'123model',
                manufacturer:'1998',
                serialNo:'1234',
                totalShipTime:'8',
                cycles:'6',
                fleet:'65',
                originator:'poojitha',
                checkType:'',
                description:'',
                routineNo:'123',
                nonRoutineNo:'456',
                micNo:'',
                defectType:'',
                defectDescription:'test',
                length:'4',
                width:'5',
                depth:'6',
                stationLocation:'',
                stringer:'',
                wl:'',
                bl:'',
                MFGpart:'',
                partDefective:'',
                MFGserial:'',
                PartTT:'',
                PartTso:'',
                detected:'',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask:'',
                corrosionType:'',
                corrosionTypeText:'',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription:'',
                floorBoardCondition:'',
                deferredSectionOptions: false,
                deferralCode:'',
                deferral:'',
                correctiveActionOptions: false,
                defectivePartDescription:'',
                modifiedpartDescription:'',
                repairedDescribe:'',
                repairDocument:'',
                chap:'',
                engineeringAuthorization:'',
                externalVisible: false,
                height:'',
                repairWidth:'',
                majorRepairOptions: false,
                repairDescription:'',
                completedBy:'',
                completedDate: new Date(),
                routineTaskCard:'',
                partNomenclature:'',
                partSerialNumber:'',
                partNumber:'',
                dteStatus:'',
                repairInspectionStatus:'',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo:'',
                rdasNo:'',
                etdNo:'',
                esmSubItemNo:'',
                inspectionThreshold:'',
                inspectionInterval:'',
                inspectionMethod:'',
                fmrLogPageMon:'',
                dteComments:'',
                updatedBy:'',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask:'',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments:'',
                qcFeedback:'',
                reviewComplete: false,
                reviewCompleteText:'',
                openStatus: false,
                completedStatus: false,
                inspector:'',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager:'',
                auditDate: new Date(),
                rejectReason:'',
                closedStatus: false,
                deletedStatus: false,
                deleteReason:''
            },
            {
                sdaId: '123457',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1:'52-Doors',
                ataCode2:'30 Cargo Door',
                model:'123model',
                manufacturer:'1998',
                serialNo:'1234',
                totalShipTime:'8',
                cycles:'6',
                fleet:'65',
                originator:'poojitha',
                checkType:'',
                description:'',
                routineNo:'123',
                nonRoutineNo:'456',
                micNo:'',
                defectType:'',
                defectDescription:'test',
                length:'4',
                width:'5',
                depth:'6',
                stationLocation:'',
                stringer:'',
                wl:'',
                bl:'',
                MFGpart:'',
                partDefective:'',
                MFGserial:'',
                PartTT:'',
                PartTso:'',
                detected:'',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask:'',
                corrosionType:'',
                corrosionTypeText:'',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription:'test',
                floorBoardCondition:'',
                deferredSectionOptions: false,
                deferralCode:'',
                deferral:'',
                correctiveActionOptions: false,
                defectivePartDescription:'',
                modifiedpartDescription:'',
                repairedDescribe:'',
                repairDocument:'',
                chap:'',
                engineeringAuthorization:'',
                externalVisible: false,
                height:'2',
                repairWidth:'',
                majorRepairOptions: false,
                repairDescription:'',
                completedBy:'',
                completedDate: new Date(),
                routineTaskCard:'',
                partNomenclature:'',
                partSerialNumber:'',
                partNumber:'',
                dteStatus:'',
                repairInspectionStatus:'',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo:'',
                rdasNo:'',
                etdNo:'',
                esmSubItemNo:'',
                inspectionThreshold:'',
                inspectionInterval:'',
                inspectionMethod:'',
                fmrLogPageMon:'',
                dteComments:'',
                updatedBy:'',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask:'',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments:'',
                qcFeedback:'',
                reviewComplete: false,
                reviewCompleteText:'',
                openStatus: false,
                completedStatus: false,
                inspector:'',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager:'',
                auditDate: new Date(),
                rejectReason:'',
                closedStatus: false,
                deletedStatus: false,
                deleteReason:''
            },
            {
                sdaId: '123458',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Completed',
                lineMaintenance: true,
                alertCode: 'C-Ground Damage'
            },
            {
                sdaId: '123459',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1:'52-Doors',
                ataCode2:'30 Cargo Door',
                model:'123model',
                manufacturer:'1998',
                serialNo:'1234',
                totalShipTime:'8',
                cycles:'6',
                fleet:'65',
                originator:'poojitha',
                checkType:'',
                description:'',
                routineNo:'123',
                nonRoutineNo:'456',
                micNo:'',
                defectType:'',
                defectDescription:'test',
                length:'4',
                width:'5',
                depth:'6',
                stationLocation:'',
                stringer:'',
                wl:'',
                bl:'',
                MFGpart:'',
                partDefective:'',
                MFGserial:'',
                PartTT:'',
                PartTso:'',
                detected:'',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask:'',
                corrosionType:'',
                corrosionTypeText:'',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription:'sadas',
                floorBoardCondition:'',
                deferredSectionOptions: false,
                deferralCode:'',
                deferral:'',
                correctiveActionOptions: false,
                defectivePartDescription:'',
                modifiedpartDescription:'',
                repairedDescribe:'',
                repairDocument:'',
                chap:'',
                engineeringAuthorization:'',
                externalVisible: false,
                height:'',
                repairWidth:'',
                majorRepairOptions: false,
                repairDescription:'',
                completedBy:'',
                completedDate: new Date(),
                routineTaskCard:'',
                partNomenclature:'',
                partSerialNumber:'',
                partNumber:'',
                dteStatus:'',
                repairInspectionStatus:'',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo:'',
                rdasNo:'',
                etdNo:'',
                esmSubItemNo:'',
                inspectionThreshold:'',
                inspectionInterval:'',
                inspectionMethod:'',
                fmrLogPageMon:'',
                dteComments:'',
                updatedBy:'',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask:'',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments:'',
                qcFeedback:'',
                reviewComplete: false,
                reviewCompleteText:'',
                openStatus: false,
                completedStatus: false,
                inspector:'',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager:'',
                auditDate: new Date(),
                rejectReason:'',
                closedStatus: false,
                deletedStatus: false,
                deleteReason:''
            },
            {
                sdaId: '123456',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1: '52-Doors',
                ataCode2: '30 Cargo Door',
                model: '123model',
                manufacturer: '1998',
                serialNo: '1234',
                totalShipTime: '8',
                cycles: '6',
                fleet: '65',
                originator: 'poojitha',
                checkType: '',
                description: '',
                routineNo: '123',
                nonRoutineNo: '456',
                micNo: '',
                defectType: '',
                defectDescription: 'test',
                length: '4',
                width: '5',
                depth: '6',
                stationLocation: '',
                stringer: '',
                wl: '',
                bl: '',
                MFGpart: '',
                partDefective: '',
                MFGserial: '',
                PartTT: '',
                PartTso: '',
                detected: '',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask: '',
                corrosionType: '',
                corrosionTypeText: '',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription: 'sadas',
                floorBoardCondition: '',
                deferredSectionOptions: false,
                deferralCode: '',
                deferral: '',
                correctiveActionOptions: false,
                defectivePartDescription: '',
                modifiedpartDescription: '',
                repairedDescribe: '',
                repairDocument: '',
                chap: '',
                engineeringAuthorization: '',
                externalVisible: false,
                height: '',
                repairWidth: '',
                majorRepairOptions: false,
                repairDescription: '',
                completedBy: '',
                completedDate: new Date(),
                routineTaskCard: '',
                partNomenclature: '',
                partSerialNumber: '',
                partNumber: '',
                dteStatus: '',
                repairInspectionStatus: '',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo: '',
                rdasNo: '',
                etdNo: '',
                esmSubItemNo: '',
                inspectionThreshold: '',
                inspectionInterval: '',
                inspectionMethod: '',
                fmrLogPageMon: '',
                dteComments: '',
                updatedBy: '',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask: '',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments: '',
                qcFeedback: '',
                reviewComplete: false,
                reviewCompleteText: '',
                openStatus: false,
                completedStatus: false,
                inspector: '',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager: '',
                auditDate: new Date(),
                rejectReason: '',
                closedStatus: false,
                deletedStatus: false,
                deleteReason: ''
                
            },
            {
                sdaId: '123460',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1: '52-Doors',
                ataCode2: '30 Cargo Door',
                model: '123model',
                manufacturer: '1998',
                serialNo: '1234',
                totalShipTime: '8',
                cycles: '6',
                fleet: '65',
                originator: 'poojitha',
                checkType: '',
                description: '',
                routineNo: '123',
                nonRoutineNo: '456',
                micNo: '',
                defectType: '',
                defectDescription: 'test',
                length: '4',
                width: '5',
                depth: '6',
                stationLocation: '',
                stringer: '',
                wl: '',
                bl: '',
                MFGpart: '',
                partDefective: '',
                MFGserial: '',
                PartTT: '',
                PartTso: '',
                detected: '',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask: '',
                corrosionType: '',
                corrosionTypeText: '',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription: 'sadas',
                floorBoardCondition: '',
                deferredSectionOptions: false,
                deferralCode: '',
                deferral: '',
                correctiveActionOptions: false,
                defectivePartDescription: '',
                modifiedpartDescription: '',
                repairedDescribe: '',
                repairDocument: '',
                chap: '',
                engineeringAuthorization: '',
                externalVisible: false,
                height: '',
                repairWidth: '',
                majorRepairOptions: false,
                repairDescription: '',
                completedBy: '',
                completedDate: new Date(),
                routineTaskCard: '',
                partNomenclature: '',
                partSerialNumber: '',
                partNumber: '',
                dteStatus: '',
                repairInspectionStatus: '',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo: '',
                rdasNo: '',
                etdNo: '',
                esmSubItemNo: '',
                inspectionThreshold: '',
                inspectionInterval: '',
                inspectionMethod: '',
                fmrLogPageMon: '',
                dteComments: '',
                updatedBy: '',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask: '',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments: '',
                qcFeedback: '',
                reviewComplete: false,
                reviewCompleteText: '',
                openStatus: false,
                completedStatus: false,
                inspector: '',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager: '',
                auditDate: new Date(),
                rejectReason: '',
                closedStatus: false,
                deletedStatus: false,
                deleteReason: ''

            },
            {
                sdaId: '123472',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1: '52-Doors',
                ataCode2: '30 Cargo Door',
                model: '123model',
                manufacturer: '1998',
                serialNo: '1234',
                totalShipTime: '8',
                cycles: '6',
                fleet: '65',
                originator: 'poojitha',
                checkType: '',
                description: '',
                routineNo: '123',
                nonRoutineNo: '456',
                micNo: '',
                defectType: '',
                defectDescription: 'test',
                length: '4',
                width: '5',
                depth: '6',
                stationLocation: '',
                stringer: '',
                wl: '',
                bl: '',
                MFGpart: '',
                partDefective: '',
                MFGserial: '',
                PartTT: '',
                PartTso: '',
                detected: '',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask: '',
                corrosionType: '',
                corrosionTypeText: '',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription: 'sadas',
                floorBoardCondition: '',
                deferredSectionOptions: false,
                deferralCode: '',
                deferral: '',
                correctiveActionOptions: false,
                defectivePartDescription: '',
                modifiedpartDescription: '',
                repairedDescribe: '',
                repairDocument: '',
                chap: '',
                engineeringAuthorization: '',
                externalVisible: false,
                height: '',
                repairWidth: '',
                majorRepairOptions: false,
                repairDescription: '',
                completedBy: '',
                completedDate: new Date(),
                routineTaskCard: '',
                partNomenclature: '',
                partSerialNumber: '',
                partNumber: '',
                dteStatus: '',
                repairInspectionStatus: '',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo: '',
                rdasNo: '',
                etdNo: '',
                esmSubItemNo: '',
                inspectionThreshold: '',
                inspectionInterval: '',
                inspectionMethod: '',
                fmrLogPageMon: '',
                dteComments: '',
                updatedBy: '',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask: '',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments: '',
                qcFeedback: '',
                reviewComplete: false,
                reviewCompleteText: '',
                openStatus: false,
                completedStatus: false,
                inspector: '',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager: '',
                auditDate: new Date(),
                rejectReason: '',
                closedStatus: false,
                deletedStatus: false,
                deleteReason: ''

            },
            {
                sdaId: '123492',
                sdrNumber: '1231',
                createDate: new Date(),
                aircraftNo: 'A380',
                station: 'DFW',
                statusText: 'Open',
                lineMaintenance: false,
                alertCode: 'C-Ground Damage',
                department: 'Inspection',
                ataCode1: '52-Doors',
                ataCode2: '30 Cargo Door',
                model: '123model',
                manufacturer: '1998',
                serialNo: '1234',
                totalShipTime: '8',
                cycles: '6',
                fleet: '65',
                originator: 'poojitha',
                checkType: '',
                description: '',
                routineNo: '123',
                nonRoutineNo: '456',
                micNo: '',
                defectType: '',
                defectDescription: 'test',
                length: '4',
                width: '5',
                depth: '6',
                stationLocation: '',
                stringer: '',
                wl: '',
                bl: '',
                MFGpart: '',
                partDefective: '',
                MFGserial: '',
                PartTT: '',
                PartTso: '',
                detected: '',
                cpcprelated: false,
                wsCorrosion: false,
                corrosionLevel: false,
                previouslyBlended: false,
                corrosionTask: '',
                corrosionType: '',
                corrosionTypeText: '',
                environment: false,
                galleySpill: false,
                blockedDrain: false,
                chemicalSpill: false,
                wetInsulationBlanket: false,
                missingFloorBoardTape: false,
                hardwareNotInstalled: false,
                poorSealingPractices: false,
                missingCorrosionInhibitor: false,
                damageOther: false,
                damageDescription: 'sadas',
                floorBoardCondition: '',
                deferredSectionOptions: false,
                deferralCode: '',
                deferral: '',
                correctiveActionOptions: false,
                defectivePartDescription: '',
                modifiedpartDescription: '',
                repairedDescribe: '',
                repairDocument: '',
                chap: '',
                engineeringAuthorization: '',
                externalVisible: false,
                height: '',
                repairWidth: '',
                majorRepairOptions: false,
                repairDescription: '',
                completedBy: '',
                completedDate: new Date(),
                routineTaskCard: '',
                partNomenclature: '',
                partSerialNumber: '',
                partNumber: '',
                dteStatus: '',
                repairInspectionStatus: '',
                fatigueCritical: false,
                stage1RTSDate: new Date(),
                duration: false,
                stage2Date: new Date(),
                stage3Date: new Date(),
                srNo: '',
                rdasNo: '',
                etdNo: '',
                esmSubItemNo: '',
                inspectionThreshold: '',
                inspectionInterval: '',
                inspectionMethod: '',
                fmrLogPageMon: '',
                dteComments: '',
                updatedBy: '',
                updatedDate: new Date(),
                dteDueDate: new Date(),
                nonCpcp: false,
                isCpcpTaskNumCorrect: false,
                cpcpTask: '',
                isCorrosionLevelCorrect: false,
                corrosion: false,
                reasonsForChange: false,
                engineeringComments: '',
                qcFeedback: '',
                reviewComplete: false,
                reviewCompleteText: '',
                openStatus: false,
                completedStatus: false,
                inspector: '',
                inspectionDate: new Date(),
                auditedStatus: false,
                manager: '',
                auditDate: new Date(),
                rejectReason: '',
                closedStatus: false,
                deletedStatus: false,
                deleteReason: ''
            }
        ]; 
        /// var form: ISDAForm;
        var result = forms.find(f => f.sdaId == id);
       // form.aircraftNo = result.aircraftNo;

        return Observable.of(result);
       // return form.length > 0 ? form[0] : undefined;
        //return this.http.get(this.endPointUrl)
        //    .map((result) => result.json());
    };
}