export const ReportOptions: any[] = [
  //General Information
  {  key: 'sdrNumber', display: 'SDA Number'},
  {  key: 'lineMaintenance', display: 'Line Maintenance'},
  {  key: 'createDate', display: 'Create Date'},
  {  key: 'alertCode', display: 'Alert Code'},
  {  key: 'sdaId', display: 'SDA ID'},
  {  key: 'ataCode1', display: 'ATA Code 1'},
  {  key: 'station', display: 'Station'},
  {  key: 'ataCode2', display: 'ATA Code 2'},
  {  key: 'department', display: 'Department'},
  {  key: 'defectDiscoveredDuring', display: 'Defect Discovered During'},
  {  key: 'unscheduledMaintenanceDescription', display: 'Unscheduled Maintenance Description'},
  {  key: 'nonRoutineNo', display: 'Non-Routine #'},
  {  key: 'micNo', display: 'MIC #'},
  {  key: 'checkType', display: 'Check Type'},
  {  key: 'routineNo', display: 'Routine #'},
  {  key: 'manufacturer', display: 'Aircraft Manufacturer'},
  {  key: 'model', display: 'Aircraft Model/Series'},
  {  key: 'serialNo', display: 'Serial #'},
  {  key: 'totalShipTime', display: 'Total Ship Time'},
  {  key: 'cyles', display: 'Cycles'},
  {  key: 'fleet', display: 'Fleet'},
  {  key: 'originator', display: 'Originator'},

  //Description and Location of Defects or Damage
  {  key: 'damageType', display: 'Damage Type'},
  {  key: 'damageDescription', display: 'Damage Description'},
  {  key: 'length', display: 'Defect Length'},
  {  key: 'width', display: 'Defect Width'},
  {  key: 'depth', display: 'Defect Depth'},
  {  key: 'aircraftStation', display: 'Aircraft Station'},
  {  key: 'stringer', display: 'Stringer'},
  {  key: 'waterLine', display: 'Water Line'},
  {  key: 'buttLine', display: 'Butt Line'},
  {  key: 'manufacturerPartNo', display: 'MFG Part #'},
  {  key: 'partDefective', display: 'Part Defective'},
  {  key: 'manufacturerSerialNo', display: 'MFG Serial #'},
  {  key: 'partTT', display: 'Part TT'},
  {  key: 'partTSO', display: 'Part TSO'},
  {  key: 'detectionMethod', display: 'How Detected'},

  //Corrosion Prevention Control Program
  {  key: 'isCPCPRelatedEvent', display: 'Is CPCP related event?'},
  {  key: 'isWideSpreadCorrosion', display: 'Widespread Corrosion'},
  {  key: 'corrosionLevel', display: 'Corrosion Level'},
  {  key: 'isPreviouslyBlended', display: 'Corroded Area Previously Blended'},
  {  key: 'corrosionTaskNo', display: 'Corrosion Task #'},
  {  key: 'corrosionType', display: 'Type of Corrosion'},
  {  key: 'causeOfDamage', display: 'Cause of Damage'},
  {  key: 'damageDescription', display: 'Damage Description'},
  {  key: 'floorBoardCondition', display: 'Floorboard condition after mat is removed'},

  //Corrective Action
  {  key: 'isDeferred', display: 'Deferred'},
  {  key: 'deferralCode', display: 'SCEPTRE Deferral Code'},
  {  key: 'deferralNo', display: 'Deferral #'},
  {  key: 'repairType', display: 'Corrective Action Repair Type'},
  {  key: 'defectivePartDescription', display: 'Defective Part Description'},
  {  key: 'modifiedPartDescription', display: 'Modified Part Description'},
  {  key: 'repairDescriptionType', display: 'Repaired Description Type'},
  {  key: 'repairDocumentType', display: 'Repair Document'},
  {  key: 'engineeringAuthorization', display: 'Engineering Authorization (EA)'},
  {  key: 'isExternallyVisible', display: 'Externally Visible?'},
  {  key: 'repairHeight', display: 'Repair Height (inches)'},
  {  key: 'repairWidth', display: 'Repair Width (inches)'},
  {  key: 'isMajorRepair', display: 'Major Repair'},
  {  key: 'majorRepairDescription', display: 'Major Repair Description'}


];